/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _CLOCK_CONFIG_H_
#define _CLOCK_CONFIG_H_

#include "fsl_common.h"

/*******************************************************************************
 * Definitions
 ******************************************************************************/

/*******************************************************************************
 ************************ BOARD_InitBootClocks function ************************
 ******************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus*/

/*!
 * @brief This function executes default configuration of clocks.
 *
 */
void BOARD_InitBootClocks(void);

#if defined(__cplusplus)
}
#endif /* __cplusplus*/

/*******************************************************************************
 ********************** Configuration ORHY_BootClockRUN ************************
 ******************************************************************************/
/*******************************************************************************
 * Definitions for ORHY_BootClockRUN configuration
 ******************************************************************************/
#define ORHY_BOOTCLOCKRUN_CORE_CLOCK               72000000U  /*!< Core clock frequency: 72000000Hz */

/*! @brief SCG set for ORHY_BootClockRUN configuration.
 */
extern const scg_sys_clk_config_t g_sysClkConfig_ORHY_BootClockRUN;
/*! @brief System OSC set for ORHY_BootClockRUN configuration.
 */
extern const scg_sosc_config_t g_scgSysOscConfig_ORHY_BootClockRUN;
/*! @brief SIRC set for ORHY_BootClockRUN configuration.
 */
extern const scg_sirc_config_t g_scgSircConfig_ORHY_BootClockRUN;
/*! @brief FIRC set for ORHY_BootClockRUN configuration.
 */
extern const scg_firc_config_t g_scgFircConfigORHY_BootClockRUN;
/*! @brief Low Power FLL set for ORHY_BootClockRUN configuration.
 */
extern const scg_lpfll_config_t g_scgLpFllConfigORHY_BootClockRUN;

/*******************************************************************************
 * API for ORHY_BootClockRUN configuration
 ******************************************************************************/
#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus*/

/*!
 * @brief This function executes configuration of clocks.
 *
 */
void ORHY_BootClockRUN(void);

#if defined(__cplusplus)
}
#endif /* __cplusplus*/

#endif /* _CLOCK_CONFIG_H_ */

