/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PERIPHERALS_H_
#define _PERIPHERALS_H_

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "fsl_common.h"
#include "fsl_lpuart.h"
#include "fsl_clock.h"
#include "fsl_ftm.h"
#include "fsl_wdog32.h"
#include "fsl_adc12.h"

#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus */

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/
/* Definitions for ORHY_InitPeripherals functional group */
/* Definition of peripheral ID */
#define COMUNICA_LPUART_PERIPHERAL LPUART2
/* Definition of the clock source frequency */
#define COMUNICA_LPUART_CLOCK_SOURCE 48000000UL
/* COMUNICA_LPUART interrupt vector ID (number). */
#define COMUNICA_LPUART_SERIAL_RX_TX_IRQN LPUART2_IRQn
/* COMUNICA_LPUART interrupt handler identifier. */
#define COMUNICA_LPUART_IRQHandler LPUART2_IRQHandler
/* Definition of peripheral ID */
#define FTM0_PERIPHERAL FTM0
/* Definition of the clock source frequency */
#define FTM0_CLOCK_SOURCE CLOCK_GetFreq(kCLOCK_BusClk)
/* FTM0 interrupt vector ID (number). */
#define FTM0_IRQN FTM0_IRQn
/* FTM0 interrupt handler identifier. */
#define FTM0_IRQHANDLER FTM0_IRQHandler
/* Definition of peripheral ID */
#define FTM1_PERIPHERAL FTM1
/* Definition of the clock source frequency */
#define FTM1_CLOCK_SOURCE CLOCK_GetFreq(kCLOCK_BusClk)
/* FTM1 interrupt vector ID (number). */
#define FTM1_IRQN FTM1_IRQn
/* FTM1 interrupt handler identifier. */
#define FTM1_IRQHANDLER FTM1_IRQHandler
/* Definition of peripheral ID */
#define LPUART1_PERIPHERAL LPUART1
/* Definition of the clock source frequency */
#define LPUART1_CLOCK_SOURCE 48000000UL
/* Definition of peripheral ID */
#define WDOG_PERIPHERAL WDOG
/* Alias for ADC0 peripheral */
#define ADC_POWER_PERIPHERAL ADC0
/* ADC_POWER interrupt vector ID (number). */
#define ADC_POWER_IRQN ADC0_IRQn
/* ADC_POWER interrupt handler identifier. */
#define ADC_POWER_IRQHANDLER ADC0_IRQHandler

/***********************************************************************************************************************
 * Global variables
 **********************************************************************************************************************/
extern const lpuart_config_t COMUNICA_LPUART_config;
extern const ftm_config_t FTM0_config;
extern const ftm_config_t FTM1_config;
extern const lpuart_config_t LPUART1_config;
extern const wdog32_config_t WDOG_config;
extern const adc12_config_t ADC_POWER_config;
extern adc12_channel_config_t ADC_POWER_channelsConfig[1];
extern const adc12_hardware_average_mode_t ADC_POWER_hardwareAverageConfig;

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/
void ORHY_InitPeripherals(void);

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void);

#if defined(__cplusplus)
}
#endif

#endif /* _PERIPHERALS_H_ */
