/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/*! @name PORTE10 (number 4), GRINDER
  @{ */

/* Symbols to be used with GPIO driver */
#define GRINDER_FGPIO FGPIOE              /*!<@brief FGPIO peripheral base pointer */
#define GRINDER_GPIO GPIOE                /*!<@brief GPIO peripheral base pointer */
#define GRINDER_GPIO_PIN_MASK (1U << 10U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define GRINDER_PORT PORTE                /*!<@brief PORT peripheral base pointer */
#define GRINDER_PIN 10U                   /*!<@brief PORT pin number */
#define GRINDER_PIN_MASK (1U << 10U)      /*!<@brief PORT pin mask */
                                          /* @} */

/*! @name PORTE4 (number 6), PORTA1
  @{ */

/* Symbols to be used with GPIO driver */
#define PORTA1_FGPIO FGPIOE             /*!<@brief FGPIO peripheral base pointer */
#define PORTA1_GPIO GPIOE               /*!<@brief GPIO peripheral base pointer */
#define PORTA1_GPIO_PIN_MASK (1U << 4U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define PORTA1_PORT PORTE               /*!<@brief PORT peripheral base pointer */
#define PORTA1_PIN 4U                   /*!<@brief PORT pin number */
#define PORTA1_PIN_MASK (1U << 4U)      /*!<@brief PORT pin mask */
                                        /* @} */

/*! @name PORTE5 (number 5), PORTA2
  @{ */

/* Symbols to be used with GPIO driver */
#define PORTA2_FGPIO FGPIOE             /*!<@brief FGPIO peripheral base pointer */
#define PORTA2_GPIO GPIOE               /*!<@brief GPIO peripheral base pointer */
#define PORTA2_GPIO_PIN_MASK (1U << 5U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define PORTA2_PORT PORTE               /*!<@brief PORT peripheral base pointer */
#define PORTA2_PIN 5U                   /*!<@brief PORT pin number */
#define PORTA2_PIN_MASK (1U << 5U)      /*!<@brief PORT pin mask */
                                        /* @} */

/*! @name PORTD1 (number 1), MAG_IN1
  @{ */

/* Symbols to be used with GPIO driver */
#define MAG_IN1_FGPIO FGPIOD             /*!<@brief FGPIO peripheral base pointer */
#define MAG_IN1_GPIO GPIOD               /*!<@brief GPIO peripheral base pointer */
#define MAG_IN1_GPIO_PIN_MASK (1U << 1U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define MAG_IN1_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define MAG_IN1_PIN 1U                   /*!<@brief PORT pin number */
#define MAG_IN1_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                         /* @} */

/*! @name PORTD0 (number 2), MAG_IN2
  @{ */

/* Symbols to be used with GPIO driver */
#define MAG_IN2_FGPIO FGPIOD             /*!<@brief FGPIO peripheral base pointer */
#define MAG_IN2_GPIO GPIOD               /*!<@brief GPIO peripheral base pointer */
#define MAG_IN2_GPIO_PIN_MASK (1U << 0U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define MAG_IN2_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define MAG_IN2_PIN 0U                   /*!<@brief PORT pin number */
#define MAG_IN2_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                         /* @} */

/*! @name PORTE11 (number 3), MAG_CTRL
  @{ */

/* Symbols to be used with GPIO driver */
#define MAG_CTRL_FGPIO FGPIOE              /*!<@brief FGPIO peripheral base pointer */
#define MAG_CTRL_GPIO GPIOE                /*!<@brief GPIO peripheral base pointer */
#define MAG_CTRL_GPIO_PIN_MASK (1U << 11U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define MAG_CTRL_PORT PORTE                /*!<@brief PORT peripheral base pointer */
#define MAG_CTRL_PIN 11U                   /*!<@brief PORT pin number */
#define MAG_CTRL_PIN_MASK (1U << 11U)      /*!<@brief PORT pin mask */
                                           /* @} */

/*! @name PORTE8 (number 17), M1_OP
  @{ */

/* Symbols to be used with PORT driver */
#define M1_OP_PORT PORTE               /*!<@brief PORT peripheral base pointer */
#define M1_OP_PIN 8U                   /*!<@brief PORT pin number */
#define M1_OP_PIN_MASK (1U << 8U)      /*!<@brief PORT pin mask */
                                       /* @} */

/*! @name PORTE9 (number 16), M1_CL
  @{ */

/* Symbols to be used with GPIO driver */
#define M1_CL_FGPIO FGPIOE             /*!<@brief FGPIO peripheral base pointer */
#define M1_CL_GPIO GPIOE               /*!<@brief GPIO peripheral base pointer */
#define M1_CL_GPIO_PIN_MASK (1U << 9U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define M1_CL_PORT PORTE               /*!<@brief PORT peripheral base pointer */
#define M1_CL_PIN 9U                   /*!<@brief PORT pin number */
#define M1_CL_PIN_MASK (1U << 9U)      /*!<@brief PORT pin mask */
                                       /* @} */

/*! @name PORTC2 (number 21), M2_OP
  @{ */

/* Symbols to be used with PORT driver */
#define M2_OP_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define M2_OP_PIN 2U                   /*!<@brief PORT pin number */
#define M2_OP_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                       /* @} */

/*! @name PORTD5 (number 24), M2_CL
  @{ */

/* Symbols to be used with GPIO driver */
#define M2_CL_FGPIO FGPIOD             /*!<@brief FGPIO peripheral base pointer */
#define M2_CL_GPIO GPIOD               /*!<@brief GPIO peripheral base pointer */
#define M2_CL_GPIO_PIN_MASK (1U << 5U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define M2_CL_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define M2_CL_PIN 5U                   /*!<@brief PORT pin number */
#define M2_CL_PIN_MASK (1U << 5U)      /*!<@brief PORT pin mask */
                                       /* @} */

/*! @name PORTB5 (number 18), COM_OP
  @{ */

/* Symbols to be used with GPIO driver */
#define COM_OP_FGPIO FGPIOB             /*!<@brief FGPIO peripheral base pointer */
#define COM_OP_GPIO GPIOB               /*!<@brief GPIO peripheral base pointer */
#define COM_OP_GPIO_PIN_MASK (1U << 5U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define COM_OP_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define COM_OP_PIN 5U                   /*!<@brief PORT pin number */
#define COM_OP_PIN_MASK (1U << 5U)      /*!<@brief PORT pin mask */
                                        /* @} */

/*! @name PORTB4 (number 19), COM_CL
  @{ */

/* Symbols to be used with PORT driver */
#define COM_CL_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define COM_CL_PIN 4U                   /*!<@brief PORT pin number */
#define COM_CL_PIN_MASK (1U << 4U)      /*!<@brief PORT pin mask */
                                        /* @} */

/*! @name PORTC5 (number 61), TEC1
  @{ */

/* Symbols to be used with GPIO driver */
#define TEC1_FGPIO FGPIOC             /*!<@brief FGPIO peripheral base pointer */
#define TEC1_GPIO GPIOC               /*!<@brief GPIO peripheral base pointer */
#define TEC1_GPIO_PIN_MASK (1U << 5U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define TEC1_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define TEC1_PIN 5U                   /*!<@brief PORT pin number */
#define TEC1_PIN_MASK (1U << 5U)      /*!<@brief PORT pin mask */
                                      /* @} */

/*! @name PORTA10 (number 58), TEC2
  @{ */

/* Symbols to be used with GPIO driver */
#define TEC2_FGPIO FGPIOA              /*!<@brief FGPIO peripheral base pointer */
#define TEC2_GPIO GPIOA                /*!<@brief GPIO peripheral base pointer */
#define TEC2_GPIO_PIN_MASK (1U << 10U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define TEC2_PORT PORTA                /*!<@brief PORT peripheral base pointer */
#define TEC2_PIN 10U                   /*!<@brief PORT pin number */
#define TEC2_PIN_MASK (1U << 10U)      /*!<@brief PORT pin mask */
                                       /* @} */

/*! @name PORTA11 (number 57), TEC3
  @{ */

/* Symbols to be used with GPIO driver */
#define TEC3_FGPIO FGPIOA              /*!<@brief FGPIO peripheral base pointer */
#define TEC3_GPIO GPIOA                /*!<@brief GPIO peripheral base pointer */
#define TEC3_GPIO_PIN_MASK (1U << 11U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define TEC3_PORT PORTA                /*!<@brief PORT peripheral base pointer */
#define TEC3_PIN 11U                   /*!<@brief PORT pin number */
#define TEC3_PIN_MASK (1U << 11U)      /*!<@brief PORT pin mask */
                                       /* @} */

/*! @name PORTA12 (number 56), TEC4
  @{ */

/* Symbols to be used with GPIO driver */
#define TEC4_FGPIO FGPIOA              /*!<@brief FGPIO peripheral base pointer */
#define TEC4_GPIO GPIOA                /*!<@brief GPIO peripheral base pointer */
#define TEC4_GPIO_PIN_MASK (1U << 12U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define TEC4_PORT PORTA                /*!<@brief PORT peripheral base pointer */
#define TEC4_PIN 12U                   /*!<@brief PORT pin number */
#define TEC4_PIN_MASK (1U << 12U)      /*!<@brief PORT pin mask */
                                       /* @} */

/*! @name PORTA13 (number 55), TEC5
  @{ */

/* Symbols to be used with GPIO driver */
#define TEC5_FGPIO FGPIOA              /*!<@brief FGPIO peripheral base pointer */
#define TEC5_GPIO GPIOA                /*!<@brief GPIO peripheral base pointer */
#define TEC5_GPIO_PIN_MASK (1U << 13U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define TEC5_PORT PORTA                /*!<@brief PORT peripheral base pointer */
#define TEC5_PIN 13U                   /*!<@brief PORT pin number */
#define TEC5_PIN_MASK (1U << 13U)      /*!<@brief PORT pin mask */
                                       /* @} */

/*! @name PORTC15 (number 29), LCD_DB0
  @{ */

/* Symbols to be used with GPIO driver */
#define LCD_DB0_FGPIO FGPIOC              /*!<@brief FGPIO peripheral base pointer */
#define LCD_DB0_GPIO GPIOC                /*!<@brief GPIO peripheral base pointer */
#define LCD_DB0_GPIO_PIN_MASK (1U << 15U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define LCD_DB0_PORT PORTC                /*!<@brief PORT peripheral base pointer */
#define LCD_DB0_PIN 15U                   /*!<@brief PORT pin number */
#define LCD_DB0_PIN_MASK (1U << 15U)      /*!<@brief PORT pin mask */
                                          /* @} */

/*! @name PORTC16 (number 28), LCD_DB1
  @{ */

/* Symbols to be used with GPIO driver */
#define LCD_DB1_FGPIO FGPIOC              /*!<@brief FGPIO peripheral base pointer */
#define LCD_DB1_GPIO GPIOC                /*!<@brief GPIO peripheral base pointer */
#define LCD_DB1_GPIO_PIN_MASK (1U << 16U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define LCD_DB1_PORT PORTC                /*!<@brief PORT peripheral base pointer */
#define LCD_DB1_PIN 16U                   /*!<@brief PORT pin number */
#define LCD_DB1_PIN_MASK (1U << 16U)      /*!<@brief PORT pin mask */
                                          /* @} */

/*! @name PORTC14 (number 30), LCD_DB2
  @{ */

/* Symbols to be used with GPIO driver */
#define LCD_DB2_FGPIO FGPIOC              /*!<@brief FGPIO peripheral base pointer */
#define LCD_DB2_GPIO GPIOC                /*!<@brief GPIO peripheral base pointer */
#define LCD_DB2_GPIO_PIN_MASK (1U << 14U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define LCD_DB2_PORT PORTC                /*!<@brief PORT peripheral base pointer */
#define LCD_DB2_PIN 14U                   /*!<@brief PORT pin number */
#define LCD_DB2_PIN_MASK (1U << 14U)      /*!<@brief PORT pin mask */
                                          /* @} */

/*! @name PORTC17 (number 27), LCD_DB3
  @{ */

/* Symbols to be used with GPIO driver */
#define LCD_DB3_FGPIO FGPIOC              /*!<@brief FGPIO peripheral base pointer */
#define LCD_DB3_GPIO GPIOC                /*!<@brief GPIO peripheral base pointer */
#define LCD_DB3_GPIO_PIN_MASK (1U << 17U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define LCD_DB3_PORT PORTC                /*!<@brief PORT peripheral base pointer */
#define LCD_DB3_PIN 17U                   /*!<@brief PORT pin number */
#define LCD_DB3_PIN_MASK (1U << 17U)      /*!<@brief PORT pin mask */
                                          /* @} */

/*! @name PORTB3 (number 31), LCD_DB4
  @{ */

/* Symbols to be used with GPIO driver */
#define LCD_DB4_FGPIO FGPIOB             /*!<@brief FGPIO peripheral base pointer */
#define LCD_DB4_GPIO GPIOB               /*!<@brief GPIO peripheral base pointer */
#define LCD_DB4_GPIO_PIN_MASK (1U << 3U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define LCD_DB4_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define LCD_DB4_PIN 3U                   /*!<@brief PORT pin number */
#define LCD_DB4_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                         /* @} */

/*! @name PORTC0 (number 26), LCD_DB5
  @{ */

/* Symbols to be used with GPIO driver */
#define LCD_DB5_FGPIO FGPIOC             /*!<@brief FGPIO peripheral base pointer */
#define LCD_DB5_GPIO GPIOC               /*!<@brief GPIO peripheral base pointer */
#define LCD_DB5_GPIO_PIN_MASK (1U << 0U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define LCD_DB5_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define LCD_DB5_PIN 0U                   /*!<@brief PORT pin number */
#define LCD_DB5_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                         /* @} */

/*! @name PORTB1 (number 33), LCD_DB6
  @{ */

/* Symbols to be used with GPIO driver */
#define LCD_DB6_FGPIO FGPIOB             /*!<@brief FGPIO peripheral base pointer */
#define LCD_DB6_GPIO GPIOB               /*!<@brief GPIO peripheral base pointer */
#define LCD_DB6_GPIO_PIN_MASK (1U << 1U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define LCD_DB6_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define LCD_DB6_PIN 1U                   /*!<@brief PORT pin number */
#define LCD_DB6_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                         /* @} */

/*! @name PORTC1 (number 25), LCD_DB7
  @{ */

/* Symbols to be used with GPIO driver */
#define LCD_DB7_FGPIO FGPIOC             /*!<@brief FGPIO peripheral base pointer */
#define LCD_DB7_GPIO GPIOC               /*!<@brief GPIO peripheral base pointer */
#define LCD_DB7_GPIO_PIN_MASK (1U << 1U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define LCD_DB7_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define LCD_DB7_PIN 1U                   /*!<@brief PORT pin number */
#define LCD_DB7_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                         /* @} */

/*! @name PORTB0 (number 34), LCD_RS
  @{ */

/* Symbols to be used with GPIO driver */
#define LCD_RS_FGPIO FGPIOB             /*!<@brief FGPIO peripheral base pointer */
#define LCD_RS_GPIO GPIOB               /*!<@brief GPIO peripheral base pointer */
#define LCD_RS_GPIO_PIN_MASK (1U << 0U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define LCD_RS_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define LCD_RS_PIN 0U                   /*!<@brief PORT pin number */
#define LCD_RS_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                        /* @} */

/*! @name PORTC9 (number 35), LCD_RW
  @{ */

/* Symbols to be used with GPIO driver */
#define LCD_RW_FGPIO FGPIOC             /*!<@brief FGPIO peripheral base pointer */
#define LCD_RW_GPIO GPIOC               /*!<@brief GPIO peripheral base pointer */
#define LCD_RW_GPIO_PIN_MASK (1U << 9U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define LCD_RW_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define LCD_RW_PIN 9U                   /*!<@brief PORT pin number */
#define LCD_RW_PIN_MASK (1U << 9U)      /*!<@brief PORT pin mask */
                                        /* @} */

/*! @name PORTC8 (number 36), LCD_CE
  @{ */

/* Symbols to be used with GPIO driver */
#define LCD_CE_FGPIO FGPIOC             /*!<@brief FGPIO peripheral base pointer */
#define LCD_CE_GPIO GPIOC               /*!<@brief GPIO peripheral base pointer */
#define LCD_CE_GPIO_PIN_MASK (1U << 8U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define LCD_CE_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define LCD_CE_PIN 8U                   /*!<@brief PORT pin number */
#define LCD_CE_PIN_MASK (1U << 8U)      /*!<@brief PORT pin mask */
                                        /* @} */

/*! @name PORTB2 (number 32), LCD_BKL
  @{ */

/* Symbols to be used with PORT driver */
#define LCD_BKL_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define LCD_BKL_PIN 2U                   /*!<@brief PORT pin number */
#define LCD_BKL_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                         /* @} */

/*! @name PORTD7 (number 22), KUNAK_TXD
  @{ */

/* Symbols to be used with PORT driver */
#define KUNAK_TXD_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define KUNAK_TXD_PIN 7U                   /*!<@brief PORT pin number */
#define KUNAK_TXD_PIN_MASK (1U << 7U)      /*!<@brief PORT pin mask */
                                           /* @} */

/*! @name PORTD6 (number 23), KUNAK_RXD
  @{ */

/* Symbols to be used with PORT driver */
#define KUNAK_RXD_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define KUNAK_RXD_PIN 6U                   /*!<@brief PORT pin number */
#define KUNAK_RXD_PIN_MASK (1U << 6U)      /*!<@brief PORT pin mask */
                                           /* @} */

/*! @name PORTE3 (number 13), KUNAK_RST
  @{ */

/* Symbols to be used with GPIO driver */
#define KUNAK_RST_FGPIO FGPIOE             /*!<@brief FGPIO peripheral base pointer */
#define KUNAK_RST_GPIO GPIOE               /*!<@brief GPIO peripheral base pointer */
#define KUNAK_RST_GPIO_PIN_MASK (1U << 3U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define KUNAK_RST_PORT PORTE               /*!<@brief PORT peripheral base pointer */
#define KUNAK_RST_PIN 3U                   /*!<@brief PORT pin number */
#define KUNAK_RST_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                           /* @} */

/*! @name PORTC6 (number 52), DEBUG_RXD
  @{ */

/* Symbols to be used with PORT driver */
#define DEBUG_RXD_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define DEBUG_RXD_PIN 6U                   /*!<@brief PORT pin number */
#define DEBUG_RXD_PIN_MASK (1U << 6U)      /*!<@brief PORT pin mask */
                                           /* @} */

/*! @name PORTC7 (number 51), DEBUG_TXD
  @{ */

/* Symbols to be used with PORT driver */
#define DEBUG_TXD_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define DEBUG_TXD_PIN 7U                   /*!<@brief PORT pin number */
#define DEBUG_TXD_PIN_MASK (1U << 7U)      /*!<@brief PORT pin mask */
                                           /* @} */

/*! @name PORTD16 (number 14), FAN
  @{ */

/* Symbols to be used with GPIO driver */
#define FAN_FGPIO FGPIOD              /*!<@brief FGPIO peripheral base pointer */
#define FAN_GPIO GPIOD                /*!<@brief GPIO peripheral base pointer */
#define FAN_GPIO_PIN_MASK (1U << 16U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define FAN_PORT PORTD                /*!<@brief PORT peripheral base pointer */
#define FAN_PIN 16U                   /*!<@brief PORT pin number */
#define FAN_PIN_MASK (1U << 16U)      /*!<@brief PORT pin mask */
                                      /* @} */

/*! @name PORTD2 (number 46), LED_5VDC
  @{ */

/* Symbols to be used with GPIO driver */
#define LED_5VDC_FGPIO FGPIOD             /*!<@brief FGPIO peripheral base pointer */
#define LED_5VDC_GPIO GPIOD               /*!<@brief GPIO peripheral base pointer */
#define LED_5VDC_GPIO_PIN_MASK (1U << 2U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define LED_5VDC_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define LED_5VDC_PIN 2U                   /*!<@brief PORT pin number */
#define LED_5VDC_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                          /* @} */

/*! @name PORTD15 (number 15), PGOOD_DC5V
  @{ */

/* Symbols to be used with GPIO driver */
#define PGOOD_DC5V_FGPIO FGPIOD              /*!<@brief FGPIO peripheral base pointer */
#define PGOOD_DC5V_GPIO GPIOD                /*!<@brief GPIO peripheral base pointer */
#define PGOOD_DC5V_GPIO_PIN_MASK (1U << 15U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define PGOOD_DC5V_PORT PORTD                /*!<@brief PORT peripheral base pointer */
#define PGOOD_DC5V_PIN 15U                   /*!<@brief PORT pin number */
#define PGOOD_DC5V_PIN_MASK (1U << 15U)      /*!<@brief PORT pin mask */
                                             /* @} */

/*! @name PORTC3 (number 20), SENSE_DC32V
  @{ */

/* Symbols to be used with PORT driver */
#define SENSE_DC32V_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define SENSE_DC32V_PIN 3U                   /*!<@brief PORT pin number */
#define SENSE_DC32V_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                             /* @} */

/*! @name PORTA5 (number 63), RST#
  @{ */

/* Symbols to be used with PORT driver */
#define RST_n_PORT PORTA               /*!<@brief PORT peripheral base pointer */
#define RST_n_PIN 5U                   /*!<@brief PORT pin number */
#define RST_n_PIN_MASK (1U << 5U)      /*!<@brief PORT pin mask */
                                       /* @} */

/*! @name PORTA4 (number 64), SWDIO
  @{ */

/* Symbols to be used with PORT driver */
#define SWDIO_PORT PORTA               /*!<@brief PORT peripheral base pointer */
#define SWDIO_PIN 4U                   /*!<@brief PORT pin number */
#define SWDIO_PIN_MASK (1U << 4U)      /*!<@brief PORT pin mask */
                                       /* @} */

/*! @name PORTC4 (number 62), SWCLK
  @{ */

/* Symbols to be used with PORT driver */
#define SWCLK_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define SWCLK_PIN 4U                   /*!<@brief PORT pin number */
#define SWCLK_PIN_MASK (1U << 4U)      /*!<@brief PORT pin mask */
                                       /* @} */

/*! @name VSS (number 10), VREFL
  @{ */
/* @} */

/*! @name VSS61 (number 40), GND
  @{ */
/* @} */

/*! @name VDD62 (number 41), DC5V
  @{ */
/* @} */

/*! @name VREFH (number 9), VREFH
  @{ */
/* @} */

/*! @name VDDA (number 8), VDDA
  @{ */
/* @} */

/*! @name VDD10 (number 7), DC5V
  @{ */
/* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void ORHY_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
