/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v8.0
processor: MKE14Z128xxx7
package_id: MKE14Z128VLH7
mcu_data: ksdk2_0
processor_version: 8.0.1
pin_labels:
- {pin_num: '64', pin_signal: PTA4/ACMP0_OUT/EWM_OUT_b/SWD_DIO, label: SWDIO, identifier: SWDIO}
- {pin_num: '63', pin_signal: PTA5/TCLK1/RESET_b, label: RST#, identifier: RST_n}
- {pin_num: '62', pin_signal: ACMP0_IN2/PTC4/FTM1_CH0/RTC_CLKOUT/EWM_IN/FTM1_QD_PHB/SWD_CLK, label: SWCLK, identifier: SWCLK}
- {pin_num: '1', pin_signal: PTD1/FTM0_CH3/LPSPI1_SIN/FTM2_CH1/FXIO_D1/TRGMUX_OUT2, label: MAG_IN1, identifier: MAG_IN1}
- {pin_num: '2', pin_signal: PTD0/FTM0_CH2/LPSPI1_SCK/FTM2_CH0/FXIO_D0/TRGMUX_OUT1, label: MAG_IN2, identifier: MAG_IN2}
- {pin_num: '3', pin_signal: PTE11/PWT_IN1/LPTMR0_ALT1/FXIO_D5/TRGMUX_OUT5, label: MAG_CTRL, identifier: MAG_CTRL}
- {pin_num: '4', pin_signal: PTE10/CLKOUT/FXIO_D4/TRGMUX_OUT4, label: GRINDER, identifier: GRINDER}
- {pin_num: '5', pin_signal: PTE5/TCLK2/FTM2_QD_PHA/FTM2_CH3/FXIO_D7/EWM_IN, label: PORTA2, identifier: PORTA2}
- {pin_num: '6', pin_signal: PTE4/BUSOUT/FTM2_QD_PHB/FTM2_CH2/FXIO_D6/EWM_OUT_b, label: PORTA1, identifier: PORTA1}
- {pin_num: '13', pin_signal: PTE3/FTM0_FLT0/LPUART2_RTS/TRGMUX_IN6, label: KUNAK_RST, identifier: COM_RST;KUNAK_RST}
- {pin_num: '14', pin_signal: PTD16/FTM0_CH1, label: FAN, identifier: FAN}
- {pin_num: '15', pin_signal: PTD15/FTM0_CH0, label: PGOOD_DC5V, identifier: PGOOD_DC5V}
- {pin_num: '16', pin_signal: DAC0_OUT/PTE9/FTM0_CH7/LPUART2_CTS, label: M1_CL, identifier: M1_CL}
- {pin_num: '17', pin_signal: ACMP0_IN3/PTE8/FTM0_CH6, label: M1_OP, identifier: M1_OP}
- {pin_num: '18', pin_signal: PTB5/FTM0_CH5/LPSPI0_PCS1/TRGMUX_IN0/ACMP1_OUT, label: COM_OP, identifier: COM_OP}
- {pin_num: '19', pin_signal: ACMP1_IN2/PTB4/FTM0_CH4/LPSPI0_SOUT/TRGMUX_IN1, label: COM_CL, identifier: COM_CL}
- {pin_num: '20', pin_signal: ADC0_SE11/ACMP0_IN4/EXTAL32/PTC3/FTM0_CH3, label: SENSE_DC32V, identifier: SENSE_DC32V}
- {pin_num: '21', pin_signal: ADC0_SE10/ACMP0_IN5/XTAL32/PTC2/FTM0_CH2, label: M2_OP, identifier: M2_OP}
- {pin_num: '11', pin_signal: EXTAL/PTB7/LPI2C0_SCL, label: EXTAL, identifier: EXTAL}
- {pin_num: '12', pin_signal: XTAL/PTB6/LPI2C0_SDA, label: XTAL, identifier: XTAL}
- {pin_num: '22', pin_signal: PTD7/LPUART2_TX/FTM2_FLT3, label: KUNAK_TXD, identifier: KUNAK_TXD}
- {pin_num: '23', pin_signal: PTD6/LPUART2_RX/FTM2_FLT2, label: KUNAK_RXD, identifier: KUNAK_RXD}
- {pin_num: '24', pin_signal: PTD5/FTM2_CH3/LPTMR0_ALT2/PWT_IN2/TRGMUX_IN7, label: M2_CL, identifier: M2_CL}
- {pin_num: '25', pin_signal: ADC0_SE9/ACMP1_IN3/PTC1/FTM0_CH1, label: LCD_DB7, identifier: LCD_DB7}
- {pin_num: '26', pin_signal: ADC0_SE8/ACMP1_IN4/PTC0/FTM0_CH0, label: LCD_DB5, identifier: LCD_DB5}
- {pin_num: '27', pin_signal: ADC0_SE15/PTC17/FTM1_FLT3/LPI2C1_SCLS, label: LCD_DB3, identifier: LCD_DB3}
- {pin_num: '28', pin_signal: ADC0_SE14/PTC16/FTM1_FLT2/LPI2C1_SDAS, label: LCD_DB1, identifier: LCD_DB1}
- {pin_num: '29', pin_signal: ADC0_SE13/PTC15/FTM1_CH3, label: LCD_DB0, identifier: LCD_DB0}
- {pin_num: '30', pin_signal: ADC0_SE12/PTC14/FTM1_CH2, label: LCD_DB2, identifier: LCD_DB2}
- {pin_num: '31', pin_signal: ADC0_SE7/PTB3/FTM1_CH1/LPSPI0_SIN/FTM1_QD_PHA/TRGMUX_IN2, label: LCD_DB4, identifier: LCD_DB4}
- {pin_num: '32', pin_signal: ADC0_SE6/PTB2/FTM1_CH0/LPSPI0_SCK/FTM1_QD_PHB/TRGMUX_IN3, label: LCD_BKL, identifier: LCD_BKL}
- {pin_num: '34', pin_signal: ADC0_SE4/PTB0/LPUART0_RX/LPSPI0_PCS0/LPTMR0_ALT3/PWT_IN3, label: LCD_RS, identifier: LCD_RS}
- {pin_num: '35', pin_signal: PTC9/LPUART1_TX/LPUART0_RTS, label: LCD_RW, identifier: LCD_RW}
- {pin_num: '47', pin_signal: ADC1_SE1/PTA3/LPI2C0_SCL/EWM_IN/LPUART0_TX, label: EXT_UART_TXD, identifier: EXT_UART_TXD}
- {pin_num: '48', pin_signal: ADC1_SE0/PTA2/LPI2C0_SDA/EWM_OUT_b/LPUART0_RX, label: EXT_UART_RXD, identifier: EXT_UART_RXD}
- {pin_num: '49', pin_signal: ADC0_SE1/ACMP0_IN1/PTA1/FTM1_CH1/LPI2C0_SDAS/FXIO_D3/FTM1_QD_PHA/LPUART0_RTS/TRGMUX_OUT0, label: EXT_UART_RTS, identifier: EXT_UART_RTS}
- {pin_num: '52', pin_signal: ADC1_SE4/PTC6/LPUART1_RX, label: DEBUG_RXD, identifier: DEBUG_RXD}
- {pin_num: '51', pin_signal: ADC1_SE5/PTC7/LPUART1_TX, label: DEBUG_TXD, identifier: DEBUG_TXD}
- {pin_num: '50', pin_signal: ADC0_SE0/ACMP0_IN0/PTA0/FTM2_CH1/LPI2C0_SCLS/FXIO_D2/FTM2_QD_PHA/LPUART0_CTS/TRGMUX_OUT3, label: EXT_UART_CTS, identifier: EXT_UART_CTS}
- {pin_num: '59', pin_signal: PTE1/LPSPI0_SIN/LPI2C0_HREQ/LPI2C1_SCL, label: EXT_SPI_SIN, identifier: EXT_SPI_SIN}
- {pin_num: '60', pin_signal: PTE0/LPSPI0_SCK/TCLK1/LPI2C1_SDA/FTM1_FLT2, label: EXT_SPI_SCK, identifier: EXT_SPI_SCK}
- {pin_num: '61', pin_signal: PTC5/FTM2_CH0/RTC_CLKOUT/LPI2C1_HREQ/FTM2_QD_PHB, label: TEC1, identifier: TEC1}
- {pin_num: '54', pin_signal: ADC1_SE10/PTE2/LPSPI0_SOUT/LPTMR0_ALT3/PWT_IN3/LPUART1_CTS, label: EXT_SPI_SOUT, identifier: EXT_SPI_SOUT}
- {pin_num: '36', pin_signal: PTC8/LPUART1_RX/LPUART0_CTS, label: LCD_CE, identifier: LCD_CE}
- {pin_num: '46', pin_signal: ADC1_SE2/PTD2/LPSPI1_SOUT/FXIO_D4/TRGMUX_IN5, label: LED_5VDC, identifier: LED_5VDC}
- {pin_num: '58', pin_signal: PTA10/LPUART0_TX/FXIO_D0, label: TEC2, identifier: TEC2}
- {pin_num: '57', pin_signal: PTA11/LPUART0_RX/FXIO_D1, label: TEC3, identifier: TEC3}
- {pin_num: '56', pin_signal: PTA12/LPI2C1_SDAS, label: TEC4, identifier: TEC4}
- {pin_num: '55', pin_signal: PTA13/LPI2C1_SCLS, label: TEC5, identifier: TEC5}
- {pin_num: '53', pin_signal: ADC1_SE11/PTE6/LPSPI0_PCS2/LPUART1_RTS, label: EXT_SPI_CS, identifier: EXT_SPI_CS}
- {pin_num: '33', pin_signal: ADC0_SE5/PTB1/LPUART0_TX/LPSPI0_SOUT/TCLK0, label: LCD_DB6, identifier: LCD_DB6}
- {pin_num: '10', pin_signal: VREFL/VSS, label: VREFL, identifier: VREFL}
- {pin_num: '40', pin_signal: VSS61, label: GND, identifier: GND}
- {pin_num: '41', pin_signal: VDD62, label: DC5V, identifier: DC5V;DC5V_1}
- {pin_num: '9', pin_signal: VREFH, label: VREFH, identifier: VREFH}
- {pin_num: '8', pin_signal: VDDA, label: VDDA, identifier: VDDA}
- {pin_num: '7', pin_signal: VDD10, label: DC5V, identifier: DC5V;DC5V_2}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_port.h"
#include "fsl_gpio.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    ORHY_InitPins();
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
ORHY_InitPins:
- options: {callFromInitBoot: 'true', prefix: '', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '4', peripheral: GPIOE, signal: 'GPIO, 10', pin_signal: PTE10/CLKOUT/FXIO_D4/TRGMUX_OUT4, direction: OUTPUT, gpio_init_state: 'true'}
  - {pin_num: '6', peripheral: GPIOE, signal: 'GPIO, 4', pin_signal: PTE4/BUSOUT/FTM2_QD_PHB/FTM2_CH2/FXIO_D6/EWM_OUT_b, direction: INPUT}
  - {pin_num: '5', peripheral: GPIOE, signal: 'GPIO, 5', pin_signal: PTE5/TCLK2/FTM2_QD_PHA/FTM2_CH3/FXIO_D7/EWM_IN, direction: INPUT}
  - {pin_num: '1', peripheral: GPIOD, signal: 'GPIO, 1', pin_signal: PTD1/FTM0_CH3/LPSPI1_SIN/FTM2_CH1/FXIO_D1/TRGMUX_OUT2, direction: INPUT}
  - {pin_num: '2', peripheral: GPIOD, signal: 'GPIO, 0', pin_signal: PTD0/FTM0_CH2/LPSPI1_SCK/FTM2_CH0/FXIO_D0/TRGMUX_OUT1, direction: INPUT, gpio_interrupt: kPORT_InterruptOrDMADisabled}
  - {pin_num: '3', peripheral: GPIOE, signal: 'GPIO, 11', pin_signal: PTE11/PWT_IN1/LPTMR0_ALT1/FXIO_D5/TRGMUX_OUT5, direction: OUTPUT, gpio_init_state: 'true'}
  - {pin_num: '17', peripheral: FTM0, signal: 'CH, 6', pin_signal: ACMP0_IN3/PTE8/FTM0_CH6, direction: OUTPUT}
  - {pin_num: '16', peripheral: GPIOE, signal: 'GPIO, 9', pin_signal: DAC0_OUT/PTE9/FTM0_CH7/LPUART2_CTS, direction: OUTPUT}
  - {pin_num: '21', peripheral: FTM0, signal: 'CH, 2', pin_signal: ADC0_SE10/ACMP0_IN5/XTAL32/PTC2/FTM0_CH2, direction: OUTPUT}
  - {pin_num: '24', peripheral: GPIOD, signal: 'GPIO, 5', pin_signal: PTD5/FTM2_CH3/LPTMR0_ALT2/PWT_IN2/TRGMUX_IN7, direction: OUTPUT}
  - {pin_num: '18', peripheral: GPIOB, signal: 'GPIO, 5', pin_signal: PTB5/FTM0_CH5/LPSPI0_PCS1/TRGMUX_IN0/ACMP1_OUT, direction: OUTPUT}
  - {pin_num: '19', peripheral: FTM0, signal: 'CH, 4', pin_signal: ACMP1_IN2/PTB4/FTM0_CH4/LPSPI0_SOUT/TRGMUX_IN1, direction: OUTPUT}
  - {pin_num: '61', peripheral: GPIOC, signal: 'GPIO, 5', pin_signal: PTC5/FTM2_CH0/RTC_CLKOUT/LPI2C1_HREQ/FTM2_QD_PHB, direction: INPUT}
  - {pin_num: '58', peripheral: GPIOA, signal: 'GPIO, 10', pin_signal: PTA10/LPUART0_TX/FXIO_D0, direction: INPUT}
  - {pin_num: '57', peripheral: GPIOA, signal: 'GPIO, 11', pin_signal: PTA11/LPUART0_RX/FXIO_D1, direction: INPUT}
  - {pin_num: '56', peripheral: GPIOA, signal: 'GPIO, 12', pin_signal: PTA12/LPI2C1_SDAS, direction: INPUT}
  - {pin_num: '55', peripheral: GPIOA, signal: 'GPIO, 13', pin_signal: PTA13/LPI2C1_SCLS, direction: INPUT}
  - {pin_num: '29', peripheral: GPIOC, signal: 'GPIO, 15', pin_signal: ADC0_SE13/PTC15/FTM1_CH3, direction: OUTPUT, pull_select: up, pull_enable: enable}
  - {pin_num: '28', peripheral: GPIOC, signal: 'GPIO, 16', pin_signal: ADC0_SE14/PTC16/FTM1_FLT2/LPI2C1_SDAS, direction: OUTPUT, pull_select: up, pull_enable: enable}
  - {pin_num: '30', peripheral: GPIOC, signal: 'GPIO, 14', pin_signal: ADC0_SE12/PTC14/FTM1_CH2, direction: OUTPUT, pull_select: up, pull_enable: enable}
  - {pin_num: '27', peripheral: GPIOC, signal: 'GPIO, 17', pin_signal: ADC0_SE15/PTC17/FTM1_FLT3/LPI2C1_SCLS, direction: OUTPUT, pull_select: up, pull_enable: enable}
  - {pin_num: '31', peripheral: GPIOB, signal: 'GPIO, 3', pin_signal: ADC0_SE7/PTB3/FTM1_CH1/LPSPI0_SIN/FTM1_QD_PHA/TRGMUX_IN2, direction: OUTPUT, pull_select: up,
    pull_enable: enable}
  - {pin_num: '26', peripheral: GPIOC, signal: 'GPIO, 0', pin_signal: ADC0_SE8/ACMP1_IN4/PTC0/FTM0_CH0, direction: OUTPUT, pull_select: up, pull_enable: enable}
  - {pin_num: '33', peripheral: GPIOB, signal: 'GPIO, 1', pin_signal: ADC0_SE5/PTB1/LPUART0_TX/LPSPI0_SOUT/TCLK0, direction: OUTPUT, pull_select: up, pull_enable: enable}
  - {pin_num: '25', peripheral: GPIOC, signal: 'GPIO, 1', pin_signal: ADC0_SE9/ACMP1_IN3/PTC1/FTM0_CH1, direction: OUTPUT, pull_select: up, pull_enable: enable}
  - {pin_num: '34', peripheral: GPIOB, signal: 'GPIO, 0', pin_signal: ADC0_SE4/PTB0/LPUART0_RX/LPSPI0_PCS0/LPTMR0_ALT3/PWT_IN3, direction: OUTPUT, pull_select: up,
    pull_enable: enable}
  - {pin_num: '35', peripheral: GPIOC, signal: 'GPIO, 9', pin_signal: PTC9/LPUART1_TX/LPUART0_RTS, direction: OUTPUT}
  - {pin_num: '36', peripheral: GPIOC, signal: 'GPIO, 8', pin_signal: PTC8/LPUART1_RX/LPUART0_CTS}
  - {pin_num: '32', peripheral: FTM1, signal: 'CH, 0', pin_signal: ADC0_SE6/PTB2/FTM1_CH0/LPSPI0_SCK/FTM1_QD_PHB/TRGMUX_IN3, direction: OUTPUT}
  - {pin_num: '22', peripheral: LPUART2, signal: TX, pin_signal: PTD7/LPUART2_TX/FTM2_FLT3}
  - {pin_num: '23', peripheral: LPUART2, signal: RX, pin_signal: PTD6/LPUART2_RX/FTM2_FLT2}
  - {pin_num: '13', peripheral: GPIOE, signal: 'GPIO, 3', pin_signal: PTE3/FTM0_FLT0/LPUART2_RTS/TRGMUX_IN6, identifier: KUNAK_RST, direction: OUTPUT}
  - {pin_num: '52', peripheral: LPUART1, signal: RX, pin_signal: ADC1_SE4/PTC6/LPUART1_RX}
  - {pin_num: '51', peripheral: LPUART1, signal: TX, pin_signal: ADC1_SE5/PTC7/LPUART1_TX}
  - {pin_num: '14', peripheral: GPIOD, signal: 'GPIO, 16', pin_signal: PTD16/FTM0_CH1, direction: OUTPUT}
  - {pin_num: '46', peripheral: GPIOD, signal: 'GPIO, 2', pin_signal: ADC1_SE2/PTD2/LPSPI1_SOUT/FXIO_D4/TRGMUX_IN5, direction: OUTPUT}
  - {pin_num: '15', peripheral: GPIOD, signal: 'GPIO, 15', pin_signal: PTD15/FTM0_CH0, direction: INPUT, gpio_interrupt: kPORT_InterruptOrDMADisabled}
  - {pin_num: '20', peripheral: ADC0, signal: 'SE, 11', pin_signal: ADC0_SE11/ACMP0_IN4/EXTAL32/PTC3/FTM0_CH3}
  - {pin_num: '63', peripheral: RCM, signal: RESET, pin_signal: PTA5/TCLK1/RESET_b}
  - {pin_num: '64', peripheral: CoreDebug, signal: SWD_DIO, pin_signal: PTA4/ACMP0_OUT/EWM_OUT_b/SWD_DIO}
  - {pin_num: '62', peripheral: CoreDebug, signal: SWD_CLK, pin_signal: ACMP0_IN2/PTC4/FTM1_CH0/RTC_CLKOUT/EWM_IN/FTM1_QD_PHB/SWD_CLK}
  - {pin_num: '10', peripheral: SUPPLY, signal: 'VSS, 0', pin_signal: VREFL/VSS}
  - {pin_num: '40', peripheral: SUPPLY, signal: 'VSS, 3', pin_signal: VSS61}
  - {pin_num: '41', peripheral: SUPPLY, signal: 'VDD, 2', pin_signal: VDD62, identifier: DC5V_1}
  - {pin_num: '9', peripheral: ADC0, signal: VREFH, pin_signal: VREFH}
  - {pin_num: '8', peripheral: SUPPLY, signal: 'VDDA, 0', pin_signal: VDDA}
  - {pin_num: '7', peripheral: SUPPLY, signal: 'VDD, 0', pin_signal: VDD10, identifier: DC5V_2}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : ORHY_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void ORHY_InitPins(void)
{
    /* Clock Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortA);
    /* Clock Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortB);
    /* Clock Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortC);
    /* Clock Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortD);
    /* Clock Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortE);

    gpio_pin_config_t TEC2_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTA10 (pin 58)  */
    GPIO_PinInit(TEC2_GPIO, TEC2_PIN, &TEC2_config);

    gpio_pin_config_t TEC3_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTA11 (pin 57)  */
    GPIO_PinInit(TEC3_GPIO, TEC3_PIN, &TEC3_config);

    gpio_pin_config_t TEC4_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTA12 (pin 56)  */
    GPIO_PinInit(TEC4_GPIO, TEC4_PIN, &TEC4_config);

    gpio_pin_config_t TEC5_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTA13 (pin 55)  */
    GPIO_PinInit(TEC5_GPIO, TEC5_PIN, &TEC5_config);

    gpio_pin_config_t LCD_RS_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTB0 (pin 34)  */
    GPIO_PinInit(LCD_RS_GPIO, LCD_RS_PIN, &LCD_RS_config);

    gpio_pin_config_t LCD_DB6_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTB1 (pin 33)  */
    GPIO_PinInit(LCD_DB6_GPIO, LCD_DB6_PIN, &LCD_DB6_config);

    gpio_pin_config_t LCD_DB4_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTB3 (pin 31)  */
    GPIO_PinInit(LCD_DB4_GPIO, LCD_DB4_PIN, &LCD_DB4_config);

    gpio_pin_config_t COM_OP_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTB5 (pin 18)  */
    GPIO_PinInit(COM_OP_GPIO, COM_OP_PIN, &COM_OP_config);

    gpio_pin_config_t LCD_DB5_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTC0 (pin 26)  */
    GPIO_PinInit(LCD_DB5_GPIO, LCD_DB5_PIN, &LCD_DB5_config);

    gpio_pin_config_t LCD_DB7_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTC1 (pin 25)  */
    GPIO_PinInit(LCD_DB7_GPIO, LCD_DB7_PIN, &LCD_DB7_config);

    gpio_pin_config_t TEC1_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTC5 (pin 61)  */
    GPIO_PinInit(TEC1_GPIO, TEC1_PIN, &TEC1_config);

    gpio_pin_config_t LCD_RW_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTC9 (pin 35)  */
    GPIO_PinInit(LCD_RW_GPIO, LCD_RW_PIN, &LCD_RW_config);

    gpio_pin_config_t LCD_DB2_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTC14 (pin 30)  */
    GPIO_PinInit(LCD_DB2_GPIO, LCD_DB2_PIN, &LCD_DB2_config);

    gpio_pin_config_t LCD_DB0_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTC15 (pin 29)  */
    GPIO_PinInit(LCD_DB0_GPIO, LCD_DB0_PIN, &LCD_DB0_config);

    gpio_pin_config_t LCD_DB1_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTC16 (pin 28)  */
    GPIO_PinInit(LCD_DB1_GPIO, LCD_DB1_PIN, &LCD_DB1_config);

    gpio_pin_config_t LCD_DB3_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTC17 (pin 27)  */
    GPIO_PinInit(LCD_DB3_GPIO, LCD_DB3_PIN, &LCD_DB3_config);

    gpio_pin_config_t MAG_IN2_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTD0 (pin 2)  */
    GPIO_PinInit(MAG_IN2_GPIO, MAG_IN2_PIN, &MAG_IN2_config);

    gpio_pin_config_t MAG_IN1_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTD1 (pin 1)  */
    GPIO_PinInit(MAG_IN1_GPIO, MAG_IN1_PIN, &MAG_IN1_config);

    gpio_pin_config_t LED_5VDC_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTD2 (pin 46)  */
    GPIO_PinInit(LED_5VDC_GPIO, LED_5VDC_PIN, &LED_5VDC_config);

    gpio_pin_config_t M2_CL_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTD5 (pin 24)  */
    GPIO_PinInit(M2_CL_GPIO, M2_CL_PIN, &M2_CL_config);

    gpio_pin_config_t PGOOD_DC5V_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTD15 (pin 15)  */
    GPIO_PinInit(PGOOD_DC5V_GPIO, PGOOD_DC5V_PIN, &PGOOD_DC5V_config);

    gpio_pin_config_t FAN_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTD16 (pin 14)  */
    GPIO_PinInit(FAN_GPIO, FAN_PIN, &FAN_config);

    gpio_pin_config_t KUNAK_RST_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTE3 (pin 13)  */
    GPIO_PinInit(KUNAK_RST_GPIO, KUNAK_RST_PIN, &KUNAK_RST_config);

    gpio_pin_config_t PORTA1_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTE4 (pin 6)  */
    GPIO_PinInit(PORTA1_GPIO, PORTA1_PIN, &PORTA1_config);

    gpio_pin_config_t PORTA2_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTE5 (pin 5)  */
    GPIO_PinInit(PORTA2_GPIO, PORTA2_PIN, &PORTA2_config);

    gpio_pin_config_t M1_CL_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTE9 (pin 16)  */
    GPIO_PinInit(M1_CL_GPIO, M1_CL_PIN, &M1_CL_config);

    gpio_pin_config_t GRINDER_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U
    };
    /* Initialize GPIO functionality on pin PTE10 (pin 4)  */
    GPIO_PinInit(GRINDER_GPIO, GRINDER_PIN, &GRINDER_config);

    gpio_pin_config_t MAG_CTRL_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U
    };
    /* Initialize GPIO functionality on pin PTE11 (pin 3)  */
    GPIO_PinInit(MAG_CTRL_GPIO, MAG_CTRL_PIN, &MAG_CTRL_config);

    /* PORTA10 (pin 58) is configured as PTA10 */
    PORT_SetPinMux(TEC2_PORT, TEC2_PIN, kPORT_MuxAsGpio);

    /* PORTA11 (pin 57) is configured as PTA11 */
    PORT_SetPinMux(TEC3_PORT, TEC3_PIN, kPORT_MuxAsGpio);

    /* PORTA12 (pin 56) is configured as PTA12 */
    PORT_SetPinMux(TEC4_PORT, TEC4_PIN, kPORT_MuxAsGpio);

    /* PORTA13 (pin 55) is configured as PTA13 */
    PORT_SetPinMux(TEC5_PORT, TEC5_PIN, kPORT_MuxAsGpio);

    /* PORTA4 (pin 64) is configured as SWD_DIO */
    PORT_SetPinMux(SWDIO_PORT, SWDIO_PIN, kPORT_MuxAlt7);

    /* PORTA5 (pin 63) is configured as RESET_b */
    PORT_SetPinMux(RST_n_PORT, RST_n_PIN, kPORT_MuxAlt7);

    /* PORTB0 (pin 34) is configured as PTB0 */
    PORT_SetPinMux(LCD_RS_PORT, LCD_RS_PIN, kPORT_MuxAsGpio);

    PORTB->PCR[0] = ((PORTB->PCR[0] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_ISF_MASK)))

                     /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                      * corresponding PE field is set. */
                     | (uint32_t)(kPORT_PullUp));

    /* PORTB1 (pin 33) is configured as PTB1 */
    PORT_SetPinMux(LCD_DB6_PORT, LCD_DB6_PIN, kPORT_MuxAsGpio);

    PORTB->PCR[1] = ((PORTB->PCR[1] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_ISF_MASK)))

                     /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                      * corresponding PE field is set. */
                     | (uint32_t)(kPORT_PullUp));

    /* PORTB2 (pin 32) is configured as FTM1_CH0 */
    PORT_SetPinMux(LCD_BKL_PORT, LCD_BKL_PIN, kPORT_MuxAlt2);

    /* PORTB3 (pin 31) is configured as PTB3 */
    PORT_SetPinMux(LCD_DB4_PORT, LCD_DB4_PIN, kPORT_MuxAsGpio);

    PORTB->PCR[3] = ((PORTB->PCR[3] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_ISF_MASK)))

                     /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                      * corresponding PE field is set. */
                     | (uint32_t)(kPORT_PullUp));

    /* PORTB4 (pin 19) is configured as FTM0_CH4 */
    PORT_SetPinMux(COM_CL_PORT, COM_CL_PIN, kPORT_MuxAlt2);

    /* PORTB5 (pin 18) is configured as PTB5 */
    PORT_SetPinMux(COM_OP_PORT, COM_OP_PIN, kPORT_MuxAsGpio);

    /* PORTC0 (pin 26) is configured as PTC0 */
    PORT_SetPinMux(LCD_DB5_PORT, LCD_DB5_PIN, kPORT_MuxAsGpio);

    PORTC->PCR[0] = ((PORTC->PCR[0] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_ISF_MASK)))

                     /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                      * corresponding PE field is set. */
                     | (uint32_t)(kPORT_PullUp));

    /* PORTC1 (pin 25) is configured as PTC1 */
    PORT_SetPinMux(LCD_DB7_PORT, LCD_DB7_PIN, kPORT_MuxAsGpio);

    PORTC->PCR[1] = ((PORTC->PCR[1] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_ISF_MASK)))

                     /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                      * corresponding PE field is set. */
                     | (uint32_t)(kPORT_PullUp));

    /* PORTC14 (pin 30) is configured as PTC14 */
    PORT_SetPinMux(LCD_DB2_PORT, LCD_DB2_PIN, kPORT_MuxAsGpio);

    PORTC->PCR[14] = ((PORTC->PCR[14] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_ISF_MASK)))

                      /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                       * corresponding PE field is set. */
                      | (uint32_t)(kPORT_PullUp));

    /* PORTC15 (pin 29) is configured as PTC15 */
    PORT_SetPinMux(LCD_DB0_PORT, LCD_DB0_PIN, kPORT_MuxAsGpio);

    PORTC->PCR[15] = ((PORTC->PCR[15] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_ISF_MASK)))

                      /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                       * corresponding PE field is set. */
                      | (uint32_t)(kPORT_PullUp));

    /* PORTC16 (pin 28) is configured as PTC16 */
    PORT_SetPinMux(LCD_DB1_PORT, LCD_DB1_PIN, kPORT_MuxAsGpio);

    PORTC->PCR[16] = ((PORTC->PCR[16] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_ISF_MASK)))

                      /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                       * corresponding PE field is set. */
                      | (uint32_t)(kPORT_PullUp));

    /* PORTC17 (pin 27) is configured as PTC17 */
    PORT_SetPinMux(LCD_DB3_PORT, LCD_DB3_PIN, kPORT_MuxAsGpio);

    PORTC->PCR[17] = ((PORTC->PCR[17] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_ISF_MASK)))

                      /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                       * corresponding PE field is set. */
                      | (uint32_t)(kPORT_PullUp));

    /* PORTC2 (pin 21) is configured as FTM0_CH2 */
    PORT_SetPinMux(M2_OP_PORT, M2_OP_PIN, kPORT_MuxAlt2);

    /* PORTC3 (pin 20) is configured as ADC0_SE11 */
    PORT_SetPinMux(SENSE_DC32V_PORT, SENSE_DC32V_PIN, kPORT_PinDisabledOrAnalog);

    /* PORTC4 (pin 62) is configured as SWD_CLK */
    PORT_SetPinMux(SWCLK_PORT, SWCLK_PIN, kPORT_MuxAlt7);

    /* PORTC5 (pin 61) is configured as PTC5 */
    PORT_SetPinMux(TEC1_PORT, TEC1_PIN, kPORT_MuxAsGpio);

    /* PORTC6 (pin 52) is configured as LPUART1_RX */
    PORT_SetPinMux(DEBUG_RXD_PORT, DEBUG_RXD_PIN, kPORT_MuxAlt2);

    /* PORTC7 (pin 51) is configured as LPUART1_TX */
    PORT_SetPinMux(DEBUG_TXD_PORT, DEBUG_TXD_PIN, kPORT_MuxAlt2);

    /* PORTC8 (pin 36) is configured as PTC8 */
    PORT_SetPinMux(LCD_CE_PORT, LCD_CE_PIN, kPORT_MuxAsGpio);

    /* PORTC9 (pin 35) is configured as PTC9 */
    PORT_SetPinMux(LCD_RW_PORT, LCD_RW_PIN, kPORT_MuxAsGpio);

    /* PORTD0 (pin 2) is configured as PTD0 */
    PORT_SetPinMux(MAG_IN2_PORT, MAG_IN2_PIN, kPORT_MuxAsGpio);

    /* Interrupt configuration on PORTD0 (pin 2): Interrupt/DMA request is disabled */
    PORT_SetPinInterruptConfig(MAG_IN2_PORT, MAG_IN2_PIN, kPORT_InterruptOrDMADisabled);

    /* PORTD1 (pin 1) is configured as PTD1 */
    PORT_SetPinMux(MAG_IN1_PORT, MAG_IN1_PIN, kPORT_MuxAsGpio);

    /* PORTD15 (pin 15) is configured as PTD15 */
    PORT_SetPinMux(PGOOD_DC5V_PORT, PGOOD_DC5V_PIN, kPORT_MuxAsGpio);

    /* Interrupt configuration on PORTD15 (pin 15): Interrupt/DMA request is disabled */
    PORT_SetPinInterruptConfig(PGOOD_DC5V_PORT, PGOOD_DC5V_PIN, kPORT_InterruptOrDMADisabled);

    /* PORTD16 (pin 14) is configured as PTD16 */
    PORT_SetPinMux(FAN_PORT, FAN_PIN, kPORT_MuxAsGpio);

    /* PORTD2 (pin 46) is configured as PTD2 */
    PORT_SetPinMux(LED_5VDC_PORT, LED_5VDC_PIN, kPORT_MuxAsGpio);

    /* PORTD5 (pin 24) is configured as PTD5 */
    PORT_SetPinMux(M2_CL_PORT, M2_CL_PIN, kPORT_MuxAsGpio);

    /* PORTD6 (pin 23) is configured as LPUART2_RX */
    PORT_SetPinMux(KUNAK_RXD_PORT, KUNAK_RXD_PIN, kPORT_MuxAlt2);

    /* PORTD7 (pin 22) is configured as LPUART2_TX */
    PORT_SetPinMux(KUNAK_TXD_PORT, KUNAK_TXD_PIN, kPORT_MuxAlt2);

    /* PORTE10 (pin 4) is configured as PTE10 */
    PORT_SetPinMux(GRINDER_PORT, GRINDER_PIN, kPORT_MuxAsGpio);

    /* PORTE11 (pin 3) is configured as PTE11 */
    PORT_SetPinMux(MAG_CTRL_PORT, MAG_CTRL_PIN, kPORT_MuxAsGpio);

    /* PORTE3 (pin 13) is configured as PTE3 */
    PORT_SetPinMux(KUNAK_RST_PORT, KUNAK_RST_PIN, kPORT_MuxAsGpio);

    /* PORTE4 (pin 6) is configured as PTE4 */
    PORT_SetPinMux(PORTA1_PORT, PORTA1_PIN, kPORT_MuxAsGpio);

    /* PORTE5 (pin 5) is configured as PTE5 */
    PORT_SetPinMux(PORTA2_PORT, PORTA2_PIN, kPORT_MuxAsGpio);

    /* PORTE8 (pin 17) is configured as FTM0_CH6 */
    PORT_SetPinMux(M1_OP_PORT, M1_OP_PIN, kPORT_MuxAlt2);

    /* PORTE9 (pin 16) is configured as PTE9 */
    PORT_SetPinMux(M1_CL_PORT, M1_CL_PIN, kPORT_MuxAsGpio);
}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
