/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : lcd.h
**     Project     : dsf
**     Processor   : MKL25Z128VLK4
**     Component   : LCDHTA
**     Version     : Component 01.022, Driver 01.00, CPU db: 3.00.000
**     Repository  : Legacy User Components
**     Compiler    : GNU C Compiler
**     Date/Time   : 2017-01-16, 17:35, # CodeGen: 2
**     Abstract    :
**          This component implements a driver for multiple 2x16 character displays.
**     Settings    :
**          Component name                                 : lcd
**          HW Interface                                   :
**            LCD Type                                     : generic
**            LCD Lines                                    : 2
**            Characters per Line                          : 8
**            Line Addresses                               :
**              Line 1                                     : 0x00
**              Line 2                                     : 0x40
**              Line 3                                     : 0x10
**              Line 4                                     : 0x50
**            LCD Enable Signal                            : Disabled
**            Read from Display                            : Enabled
**              R/W signal                                 : CtrlPin
**              Check Busy Flag                            : yes
**            Wait (us)                                    : 0
**            E signal                                     : CtrlPin
**            E2                                           : Disabled
**            RS signal                                    : CtrlPin
**            Data/Control Bus                             :
**              Data/Control Bus Width                     : 8bit
**              DB0..DB3                                   : Enabled
**                DB0                                      : DBpin
**                DB1                                      : DBpin
**                DB2                                      : DBpin
**                DB3                                      : DBpin
**              DB4..DB7                                   : Enabled
**                DB4                                      : DBpin
**                DB5                                      : DBpin
**                DB6                                      : DBpin
**                DB7                                      : DBpin
**              Bits/Byte Bus                              : Disabled
**          System Interface                               :
**            Wait                                         : WAIT1
**     Contents    :
**         WriteLCDCommand  - void lcd_WriteLCDCommand(uint8_t cmd);
**         Write            - void lcd_Write(uint8_t ch);
**         WriteLn          - void lcd_WriteLn(void);
**         WriteLineStr     - void lcd_WriteLineStr(uint8_t line, uint8_t *str);
**         WriteString      - void lcd_WriteString(uint8_t *str);
**         LoadSoftChar     - void lcd_LoadSoftChar(uint8_t charCode, uint8_t *softChar);
**         ShiftLeft        - void lcd_ShiftLeft(void);
**         ShiftRight       - void lcd_ShiftRight(void);
**         GotoXY           - void lcd_GotoXY(uint8_t line, uint8_t column);
**         SetEntryMode     - void lcd_SetEntryMode(bool increment, bool shiftLeft);
**         CursorOn         - void lcd_CursorOn(void);
**         CursorOff        - void lcd_CursorOff(void);
**         CursorShiftRight - void lcd_CursorShiftRight(void);
**         CursorShiftLeft  - void lcd_CursorShiftLeft(void);
**         BlinkingOn       - void lcd_BlinkingOn(void);
**         BlinkingOff      - void lcd_BlinkingOff(void);
**         Home             - void lcd_Home(void);
**         Line             - void lcd_Line(uint8_t line);
**         Clear            - void lcd_Clear(void);
**         UseDisplay       - uint8_t lcd_UseDisplay(uint8_t display);
**
**     License   :  Open Source (LGPL)
**     Copyright : (c) Copyright Erich Styger, 2008-2014, all rights reserved.
**     http      : www.mcuoneclipse.com
**     This an open source software implementing software using Processor Expert.
**     This is a free software and is opened for education,  research  and commercial developments under license policy of following terms:
**     * This is a free software and there is NO WARRANTY.
**     * No restriction on use. You can use, modify and redistribute it for personal, non-profit or commercial product UNDER YOUR RESPONSIBILITY.
**     * Redistributions of source code must retain the above copyright notice.
** ###################################################################*/
/*!
** @file lcd.h
** @version 01.00
** @brief
**          This component implements a driver for multiple 2x16 character displays.
*/
/*!
**  @addtogroup lcd_module lcd module documentation
**  @{
*/

#ifndef __lcd_H
#define __lcd_H

/* MODULE lcd. */

#include <stdbool.h>

#include "wait.h"

/* ID's for the soft characters which can be used as first argument for lcd_LoadSoftChar().
  Note that ID's can start with zero, but if you want to use a zero byte in lcd_WriteString()
  then this would be the zero delimiter byte, so not very useful. */
enum
{
  lcd_SOFTCHAR_MAG_ARROW = 1,
  lcd_SOFTCHAR_LEFT_UP_BOX,
  lcd_SOFTCHAR_CENTER_UP_BOX,
  lcd_SOFTCHAR_RIGHT_UP_BOX,
  lcd_SOFTCHAR_LEFT_DOWN_BOX,
  lcd_SOFTCHAR_CENTER_DOWN_BOX,
  lcd_SOFTCHAR_RIGHT_DOWN_BOX
};

/* support for custom soft characters in the display which can be used with lcd_LoadSoftChar() */
extern const uint8_t lcd_SoftCharMAG[8];    /* MAG */
extern const uint8_t lcd_SoftCharARROW[8];  /* ARROW */

//dosificador
//parte superior
extern const uint8_t lcd_SoftCharLEFTBOXUP[64];
extern const uint8_t lcd_SoftCharCENTERBOXUP[64];
extern const uint8_t lcd_SoftCharRIGHTBOXUP[64];
//parte inferior
extern const uint8_t lcd_SoftCharLEFTBOXDOWN[64];
extern const uint8_t lcd_SoftCharCENTERBOXDOWN[64];
extern const uint8_t lcd_SoftCharRIGHTBOXDOWN[64];

#define lcd_MAX_LCD_LINE_CHARS  8 /* number of chars of the LCD on a line */


void lcd_WriteLCDData(uint8_t ch);
/*
** ===================================================================
**     Method      :  lcd_WriteLCDData (component LCDHTA)
**
**     Description :
**         Writes data to the display
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/

void lcd_Init(void);
/*
** ===================================================================
**     Method      :  lcd_Init (component LCDHTA)
**
**     Description :
**         Display driver initialization routine.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/

void lcd_Clear(void);
/*
** ===================================================================
**     Method      :  lcd_Clear (component LCDHTA)
**     Description :
**         Clears the display and moves the cursor to the first line.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

void lcd_Home(void);
/*
** ===================================================================
**     Method      :  lcd_Home (component LCDHTA)
**     Description :
**         Moves the cursor to the beginning of the first line.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

void lcd_GotoXY(uint8_t line, uint8_t column);
/*
** ===================================================================
**     Method      :  lcd_GotoXY (component LCDHTA)
**     Description :
**         Places the cursor on a specified position on the display.
**     Parameters  :
**         NAME            - DESCRIPTION
**         line            - Line number starting with 1
**         column          - Column number starting with 1
**     Returns     : Nothing
** ===================================================================
*/

void lcd_ShiftLeft(void);
/*
** ===================================================================
**     Method      :  lcd_ShiftLeft (component LCDHTA)
**     Description :
**         Shifts all characters to the left.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

#define lcd_Write(ch)   lcd_WriteLCDData((uint8_t)ch)
/*
** ===================================================================
**     Method      :  lcd_Write (component LCDHTA)
**     Description :
**         Write a single character to the display
**     Parameters  :
**         NAME            - DESCRIPTION
**         ch              - Character to write
**     Returns     : Nothing
** ===================================================================
*/

void lcd_WriteLn(void);
/*
** ===================================================================
**     Method      :  lcd_WriteLn (component LCDHTA)
**     Description :
**         Writes a new line to the display
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

void lcd_WriteString(char *str);
/*
** ===================================================================
**     Method      :  lcd_WriteString (component LCDHTA)
**     Description :
**         Writes a string to the display at the current cursor
**         position.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * str             - Pointer to string (zero byte terminated)
**                           to write to the display
**     Returns     : Nothing
** ===================================================================
*/

void lcd_WriteLineStr(uint8_t line, char *str);
/*
** ===================================================================
**     Method      :  lcd_WriteLineStr (component LCDHTA)
**     Description :
**         Writes a full line to the display (clears the rest of the
**         line).
**     Parameters  :
**         NAME            - DESCRIPTION
**         line            - Line number (starting with 1).
**       * str             - Pointer to the string which should be
**                           shown on the display.
**     Returns     : Nothing
** ===================================================================
*/

/*
** ===================================================================
**     Method      :  lcd_WriteFullStr (component LCDHTA)
**     Description :
**         Writes a full text to the display, starting from the 1st
**         line. If text is longer than lcd_MAX_LCD_LINE_CHARS chars,
**         jumps at the whitespace.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * str             - Pointer to the string which should be
**                           shown on the display.
**     Returns     : Nothing
** ===================================================================
*/
void lcd_WriteFullStr(char *str);

void lcd_LoadSoftChar(uint8_t charCode, uint8_t *softChar);
/*
** ===================================================================
**     Method      :  lcd_LoadSoftChar (component LCDHTA)
**     Description :
**         Loads a user defined (softchar) into the display CGRAM.
**     Parameters  :
**         NAME            - DESCRIPTION
**         charCode        - The character code to be defined
**                           (0..7)
**       * softChar        - Pointer to an array of 8 bytes
**                           defining the soft character
**                           Example of the soft character 'ü':
**                           const uint8_t SoftCharUE[8] = { // ü
**                           0x11, 0x00, 0x11, 0x11, 0x11, 0x13, 0x0d, 0
**                           //  X...X
**                           //  .....
**                           //  X...X
**                           //  X...X
**                           //  X...X
**                           //  X..XX
**                           //  .XX.X
**                           };
**     Returns     : Nothing
** ===================================================================
*/

void lcd_Line(uint8_t line);
/*
** ===================================================================
**     Method      :  lcd_Line (component LCDHTA)
**     Description :
**         Sets the current line.
**     Parameters  :
**         NAME            - DESCRIPTION
**         line            - Line number, starting with 1
**     Returns     : Nothing
** ===================================================================
*/

void lcd_ShiftRight(void);
/*
** ===================================================================
**     Method      :  lcd_ShiftRight (component LCDHTA)
**     Description :
**         Shifts all characters to the right.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

void lcd_CursorOn(void);
/*
** ===================================================================
**     Method      :  lcd_CursorOn (component LCDHTA)
**     Description :
**         Enables the cursor.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

void lcd_CursorOff(void);
/*
** ===================================================================
**     Method      :  lcd_CursorOff (component LCDHTA)
**     Description :
**         Disables the cursor.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

void lcd_BlinkingOn(void);
/*
** ===================================================================
**     Method      :  lcd_BlinkingOn (component LCDHTA)
**     Description :
**         Sends the display off command to the display.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

void lcd_BlinkingOff(void);
/*
** ===================================================================
**     Method      :  lcd_BlinkingOff (component LCDHTA)
**     Description :
**         Puts the display in blinking off mode.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

void lcd_SetEntryMode(bool increment, bool shiftLeft);
/*
** ===================================================================
**     Method      :  lcd_SetEntryMode (component LCDHTA)
**     Description :
**         Configures the display entry mode, if the cursor has to
**         shift and/or if the display shall shift content while
**         displaying text.
**     Parameters  :
**         NAME            - DESCRIPTION
**         increment       - Increments (TRUE) or
**                           decrements (FALSE) the display address by 1
**                           when a character code is written into or
**                           read from DDRAM. The cursor or blinking
**                           moves to the right when incremented by 1
**                           and to the left when decremented by 1.
**         shiftLeft       - The display does not shift if
**                           the 'shift' is FALSE. If 'shift' is TRUE,
**                           it will seem as if the cursor does not move
**                           but the display does.
**     Returns     : Nothing
** ===================================================================
*/

void lcd_WaitForLCDReady(void);
/*
** ===================================================================
**     Method      :  lcd_WaitForLCDReady (component LCDHTA)
**
**     Description :
**         Waits until the display is ready
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/

uint8_t lcd_UseDisplay(uint8_t display);
/*
** ===================================================================
**     Method      :  lcd_UseDisplay (component LCDHTA)
**     Description :
**
**     Parameters  :
**         NAME            - DESCRIPTION
**         display         - Has to be either 1 (top display,
**                           using E1) or 2 (bottom display, using E2)
**     Returns     :
**         ---             - Error code
** ===================================================================
*/

void lcd_CursorShiftRight(void);
/*
** ===================================================================
**     Method      :  lcd_CursorShiftRight (component LCDHTA)
**     Description :
**         Shift the cursor to the right.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

void lcd_CursorShiftLeft(void);
/*
** ===================================================================
**     Method      :  lcd_CursorShiftLeft (component LCDHTA)
**     Description :
**         Shift the cursor to the left.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

void lcd_WriteLCDCommand(uint8_t cmd);
/*
** ===================================================================
**     Method      :  lcd_WriteLCDCommand (component LCDHTA)
**     Description :
**         Writes a command to the display
**     Parameters  :
**         NAME            - DESCRIPTION
**         cmd             - command passed to the LCD
**     Returns     : Nothing
** ===================================================================
*/

/* END lcd. */

#endif
/* ifndef __lcd_H */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.5 [05.21]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
