/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : wait.h
**     Project     : dsf
**     Processor   : MKL25Z128VLK4
**     Component   : Wait
**     Version     : Component 01.069, Driver 01.00, CPU db: 3.00.000
**     Repository  : Legacy User Components
**     Compiler    : GNU C Compiler
**     Date/Time   : 2017-01-16, 18:19, # CodeGen: 5
**     Abstract    :
**          Implements busy waiting routines.
**     Settings    :
**          Component name                                 : wait
**          SDK                                            : KSDK1
**          Manual Clock Values                            : Disabled
**          Delay100usFunction                             : Delay100US
**          RTOS                                           : Disabled
**          Watchdog                                       : Disabled
**     Contents    :
**         Wait10Cycles   - void wait_Wait10Cycles(void);
**         Wait100Cycles  - void wait_Wait100Cycles(void);
**         WaitCycles     - void wait_WaitCycles(uint16_t cycles);
**         WaitLongCycles - void wait_WaitLongCycles(uint32_t cycles);
**         Waitms         - void wait_Waitms(uint16_t ms);
**         Waitus         - void wait_Waitus(uint16_t us);
**         Waitns         - void wait_Waitns(uint16_t ns);
**         WaitOSms       - void wait_WaitOSms(void);
**
**     License   : Open Source (LGPL)
**     Copyright : Erich Styger, 2013-2016, all rights reserved.
**     Web       : www.mcuoneclipse.com
**     This an open source software implementing waiting routines using Processor Expert.
**     This is a free software and is opened for education,  research  and commercial developments under license policy of following terms:
**     * This is a free software and there is NO WARRANTY.
**     * No restriction on use. You can use, modify and redistribute it for personal, non-profit or commercial product UNDER YOUR RESPONSIBILITY.
**     * Redistributions of source code must retain the above copyright notice.
** ###################################################################*/
/*!
** @file wait.h
** @version 01.00
** @brief
**          Implements busy waiting routines.
*/         
/*!
**  @addtogroup wait_module wait module documentation
**  @{
*/         

#ifndef __wait_H
#define __wait_H

/* MODULE wait. */

#include <stdint.h>

#include "board.h"

#ifdef __cplusplus
extern "C" {
#endif


extern uint32_t SystemCoreClock; /* clock frequency variable defined system_<device>.h of the SDK */
#define wait_INSTR_CLOCK_HZ       SystemCoreClock  /* core clock frequency in Hz */

#define wait_NofCyclesMs(ms, hz)  ((ms)*((hz)/1000)) /* calculates the needed cycles based on bus clock frequency */
#define wait_NofCyclesUs(us, hz)  ((us)*(((hz)/1000)/1000)) /* calculates the needed cycles based on bus clock frequency */
#define wait_NofCyclesNs(ns, hz)  (((ns)*(((hz)/1000)/1000))/1000) /* calculates the needed cycles based on bus clock frequency */


#define wait_WAIT_C(cycles) \
     ( (cycles)<=10 ? \
          wait_Wait10Cycles() \
        : wait_WaitCycles((uint16_t)cycles) \
      )                                      /*!< wait for some cycles */


void wait_Wait10Cycles(void);
/*
** ===================================================================
**     Method      :  wait_Wait10Cycles (component Wait)
**     Description :
**         Wait for 10 CPU cycles.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

void wait_Wait100Cycles(void);
/*
** ===================================================================
**     Method      :  wait_Wait100Cycles (component Wait)
**     Description :
**         Wait for 100 CPU cycles.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

void wait_WaitCycles(uint16_t cycles);
/*
** ===================================================================
**     Method      :  wait_WaitCycles (component Wait)
**     Description :
**         Wait for a specified number of CPU cycles (16bit data type).
**     Parameters  :
**         NAME            - DESCRIPTION
**         cycles          - The number of cycles to wait.
**     Returns     : Nothing
** ===================================================================
*/

void wait_Waitms(uint16_t ms);
/*
** ===================================================================
**     Method      :  wait_Waitms (component Wait)
**     Description :
**         Wait for a specified time in milliseconds.
**     Parameters  :
**         NAME            - DESCRIPTION
**         ms              - How many milliseconds the function has to
**                           wait
**     Returns     : Nothing
** ===================================================================
*/

/* we are having a static clock configuration: implement as macro/inlined version */
#define wait_Waitus(us)  \
        /*lint -save -e(505,506,522) Constant value Boolean, Redundant left argument to comma. */\
       (  ((wait_NofCyclesUs((us),wait_INSTR_CLOCK_HZ)==0)||(us)==0) ? \
          (void)0 : \
          ( ((us)/1000)==0 ? (void)0 : wait_Waitms((uint16_t)((us)/1000))) \
          , (wait_NofCyclesUs(((us)%1000), wait_INSTR_CLOCK_HZ)==0) ? (void)0 : \
            wait_WAIT_C(wait_NofCyclesUs(((us)%1000), wait_INSTR_CLOCK_HZ)) \
       /*lint -restore */\
       )
/*
** ===================================================================
**     Method      :  wait_Waitus (component Wait)
**     Description :
**         Wait for a specified time in microseconds.
**     Parameters  :
**         NAME            - DESCRIPTION
**         us              - How many microseconds the function has to
**                           wait
**     Returns     : Nothing
** ===================================================================
*/

/* we are having a static clock configuration: implement as macro/inlined version */
#define wait_Waitns(ns)  \
        /*lint -save -e(505,506,522) Constant value Boolean, Redundant left argument to comma. */\
       (  ((wait_NofCyclesNs((ns), wait_INSTR_CLOCK_HZ)==0)||(ns)==0) ? \
          (void)0 : \
          wait_Waitus((ns)/1000) \
          , (wait_NofCyclesNs((ns)%1000, wait_INSTR_CLOCK_HZ)==0) ? \
              (void)0 : \
              wait_WAIT_C(wait_NofCyclesNs(((ns)%1000), wait_INSTR_CLOCK_HZ)) \
       /*lint -restore */\
       )
/*
** ===================================================================
**     Method      :  wait_Waitns (component Wait)
**     Description :
**         Wait for a specified time in nano seconds.
**     Parameters  :
**         NAME            - DESCRIPTION
**         ns              - How many ns the function has to wait
**     Returns     : Nothing
** ===================================================================
*/

#define wait_WaitOSms(ms) \
  wait_Waitms(ms) /* no RTOS used, so use normal wait */
/*
** ===================================================================
**     Method      :  wait_WaitOSms (component Wait)
**     Description :
**         If an RTOS is enabled, this routine will use a non-blocking
**         wait method. Otherwise it will do a busy/blocking wait.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

#ifdef __cplusplus
}  /* extern "C" */
#endif

void wait_WaitLongCycles(uint32_t cycles);
/*
** ===================================================================
**     Method      :  wait_WaitLongCycles (component Wait)
**     Description :
**         Wait for a specified number of CPU cycles (32bit data type).
**     Parameters  :
**         NAME            - DESCRIPTION
**         cycles          - The number of cycles to wait.
**     Returns     : Nothing
** ===================================================================
*/

/* END wait. */

#endif
/* ifndef __wait_H */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.5 [05.21]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
